POST http://localhost:8080/api/user/
Content-Type: application/json

{
  "githubUsername": "nielsengoncalves"
}

###
GET http://localhost:8080/api/user/nielsengoncalves
Content-Type: application/json

###
DELETE http://localhost:8080/api/user/nielsengoncalves
Content-Type: application/json
